-- One row per question asked through /api/ask — the data behind
-- Settings ▸ Workspace 分析.
--
-- Until now the only per-workspace signals were ask_workspaces.request_count
-- (a bare counter) and the spend ledger, llm_usage_events — which only sees
-- questions that reached a model. A question the knowledge base could not
-- answer never reaches one, so it left no trace anywhere, and those are the
-- questions the dashboard most needs to show.
--
-- Who asked: internal /ask stores the signed-in user's id. Workspace and demo
-- visitors are anonymous, so their browser sends a random id it keeps in
-- localStorage (visitor_id). That counts browsers, not people.
--
-- The question text is what people typed. RLS is on with no policies, so only
-- the service role reads it, and ask_requests_redact() clears it after 90 days
-- (called from the daily reindex-products cron).
--
-- The id is generated by the route and sent back to the client, which uses it
-- to leave 👍/👎 feedback on that answer (/api/ask/feedback).

create table if not exists public.ask_requests (
  id              uuid primary key,
  created_at      timestamptz not null default now(),
  channel         text not null check (channel in ('workspace', 'internal', 'demo')),
  workspace       text,
  user_id         uuid,
  visitor_id      text check (visitor_id is null or length(visitor_id) <= 64),
  question        text,
  question_chars  integer not null default 0,
  model           text,
  persona         text,
  profile         text,
  match_count     integer not null default 0,
  top_similarity  real,
  cited           jsonb not null default '[]'::jsonb,
  outcome         text not null
                  check (outcome in ('answered', 'no_match', 'error', 'stopped', 'rate_limited')),
  error           text,
  retrieval_ms    integer,
  ttft_ms         integer,
  duration_ms     integer,
  feedback        smallint check (feedback in (-1, 1)),
  feedback_at     timestamptz
);

-- "key" everywhere below = the workspace slug, or 'internal' / 'demo'.
create index if not exists ask_requests_created_at_idx
  on public.ask_requests (created_at desc);
create index if not exists ask_requests_key_created_at_idx
  on public.ask_requests ((coalesce(workspace, channel)), created_at desc);

alter table public.ask_requests enable row level security;
revoke all on public.ask_requests from anon, authenticated;

-- ── Aggregates for the dashboard ────────────────────────────────────────────
-- p_low_sim: an answered question whose best retrieved chunk scored below
-- this counts as a knowledge gap. Retrieval's own floor is 0.3; 0.45 is a
-- starting point to tune once there is real data.

create or replace function public.ask_analytics_summary(
  p_from timestamptz, p_to timestamptz, p_low_sim real default 0.45
)
returns table (
  key text, questions integer, answered integer, no_match integer, errors integer,
  stopped integer, rate_limited integer, low_similarity integer, visitors integer,
  helpful integer, unhelpful integer, first_token_p50_ms integer
)
language sql stable set search_path = public
as $$
  select
    coalesce(workspace, channel),
    count(*) filter (where outcome <> 'rate_limited')::int,
    count(*) filter (where outcome = 'answered')::int,
    count(*) filter (where outcome = 'no_match')::int,
    count(*) filter (where outcome = 'error')::int,
    count(*) filter (where outcome = 'stopped')::int,
    count(*) filter (where outcome = 'rate_limited')::int,
    count(*) filter (where outcome = 'answered' and top_similarity < p_low_sim)::int,
    count(distinct coalesce(user_id::text, visitor_id)) filter (where outcome <> 'rate_limited')::int,
    count(*) filter (where feedback = 1)::int,
    count(*) filter (where feedback = -1)::int,
    (percentile_cont(0.5) within group (order by ttft_ms))::int
  from public.ask_requests
  where created_at >= p_from and created_at < p_to
  group by 1
$$;

-- Days are Taiwan days, so a 09:00 question isn't filed under yesterday.
create or replace function public.ask_analytics_daily(
  p_from timestamptz, p_to timestamptz, p_key text default null
)
returns table (key text, day date, answered integer, no_match integer, errors integer)
language sql stable set search_path = public
as $$
  select
    coalesce(workspace, channel),
    (created_at at time zone 'Asia/Taipei')::date,
    count(*) filter (where outcome in ('answered', 'stopped'))::int,
    count(*) filter (where outcome = 'no_match')::int,
    count(*) filter (where outcome = 'error')::int
  from public.ask_requests
  where created_at >= p_from and created_at < p_to
    and outcome <> 'rate_limited'
    and (p_key is null or coalesce(workspace, channel) = p_key)
  group by 1, 2
$$;

-- Knowledge gaps: nothing found, a weak best match, or a 👎. The same
-- question asked twice (case / spacing aside) is one row with times = 2.
create or replace function public.ask_analytics_gaps(
  p_from timestamptz, p_to timestamptz, p_key text default null,
  p_low_sim real default 0.45, p_limit integer default 20
)
returns table (key text, question text, times integer, last_at timestamptz, reason text, best_similarity real)
language sql stable set search_path = public
as $$
  select
    coalesce(workspace, channel),
    (array_agg(question order by created_at desc))[1],
    count(*)::int,
    max(created_at),
    case
      when bool_or(outcome = 'no_match') then 'no_match'
      when bool_or(feedback = -1) then 'unhelpful'
      else 'low_similarity'
    end,
    max(top_similarity)
  from public.ask_requests
  where created_at >= p_from and created_at < p_to
    and question is not null
    and (outcome = 'no_match' or feedback = -1 or (outcome = 'answered' and top_similarity < p_low_sim))
    and (p_key is null or coalesce(workspace, channel) = p_key)
  group by coalesce(workspace, channel), lower(regexp_replace(btrim(question), '\s+', ' ', 'g'))
  order by count(*) desc, max(created_at) desc
  limit p_limit
$$;

create or replace function public.ask_analytics_sources(
  p_from timestamptz, p_to timestamptz, p_key text default null, p_limit integer default 8
)
returns table (title text, source_type text, times integer)
language sql stable set search_path = public
as $$
  select c->>'title', c->>'source_type', count(*)::int
  from public.ask_requests r
  cross join lateral jsonb_array_elements(r.cited) as c
  where r.created_at >= p_from and r.created_at < p_to
    and (p_key is null or coalesce(r.workspace, r.channel) = p_key)
  group by 1, 2
  order by 3 desc, 1
  limit p_limit
$$;

-- Spend comes from the ledger, not from ask_requests: it is the record of
-- what was billed, it already carries the workspace in `ref`, and it goes
-- back to 2026-08-08 rather than to the day this table was created.
-- BYOK calls are counted but not costed — that money isn't the company's.
create or replace function public.ask_analytics_spend(
  p_from timestamptz, p_to timestamptz, p_key text default null
)
returns table (key text, model text, calls integer, tokens bigint, cost numeric, byok_calls integer)
language sql stable set search_path = public
as $$
  select
    coalesce(ref, 'internal'),
    model,
    count(*)::int,
    coalesce(sum(total_tokens), 0)::bigint,
    coalesce(sum(cost) filter (where not is_byok), 0),
    count(*) filter (where is_byok)::int
  from public.llm_usage_events
  where surface = 'ask' and created_at >= p_from and created_at < p_to
    and (p_key is null or coalesce(ref, 'internal') = p_key)
  group by 1, 2
$$;

create or replace function public.ask_analytics_last_seen()
returns table (key text, last_at timestamptz)
language sql stable set search_path = public
as $$
  select coalesce(workspace, channel), max(created_at)
  from public.ask_requests
  where outcome <> 'rate_limited'
  group by 1
$$;

create or replace function public.ask_requests_redact(p_days integer default 90)
returns integer
language sql volatile set search_path = public
as $$
  with cleared as (
    update public.ask_requests
       set question = null
     where question is not null
       and created_at < now() - make_interval(days => p_days)
    returning 1
  )
  select count(*)::int from cleared
$$;

revoke all on function public.ask_analytics_summary(timestamptz, timestamptz, real) from public, anon, authenticated;
revoke all on function public.ask_analytics_daily(timestamptz, timestamptz, text) from public, anon, authenticated;
revoke all on function public.ask_analytics_gaps(timestamptz, timestamptz, text, real, integer) from public, anon, authenticated;
revoke all on function public.ask_analytics_sources(timestamptz, timestamptz, text, integer) from public, anon, authenticated;
revoke all on function public.ask_analytics_spend(timestamptz, timestamptz, text) from public, anon, authenticated;
revoke all on function public.ask_analytics_last_seen() from public, anon, authenticated;
revoke all on function public.ask_requests_redact(integer) from public, anon, authenticated;
grant execute on function public.ask_analytics_summary(timestamptz, timestamptz, real) to service_role;
grant execute on function public.ask_analytics_daily(timestamptz, timestamptz, text) to service_role;
grant execute on function public.ask_analytics_gaps(timestamptz, timestamptz, text, real, integer) to service_role;
grant execute on function public.ask_analytics_sources(timestamptz, timestamptz, text, integer) to service_role;
grant execute on function public.ask_analytics_spend(timestamptz, timestamptz, text) to service_role;
grant execute on function public.ask_analytics_last_seen() to service_role;
grant execute on function public.ask_requests_redact(integer) to service_role;
